name: Container Images from PostgreSQL sources

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pg_repo:
        description: "Name of the target PG repository"
        required: true
        default: "https://git.postgresql.org/git/postgresql.git"
      pg_branch:
        description: "Name of the branch in the target PG repository"
        required: true
        default: "master"
      major_version:
        description: "PostgreSQL major version (leave empty for default)"
        required: false
      extra_tag:
        description: "Optional extra tag (make sure it starts with the PG major)"
        required: false

# set up environment variables to be used across all the jobs
env:
  REGISTRY: "ghcr.io/${{ github.repository_owner }}/postgresql-trunk"

defaults:
  run:
    # default failure handling for shell scripts in 'run' steps
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test-forks:
    name: test-forks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git
        run: |
          image_tag=$( (git symbolic-ref -q --short HEAD || git describe --tags --exact-match) | tr / -)
          echo $image_tag

  test-slash:
    name: test-slash
    runs-on: ubuntu-24.04
    steps:
      - name: Resolve Git reference
        uses: xt0rted/pull-request-comment-branch@v3
        id: refs

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.refs.outputs.head_sha }}
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Git
        run: |
          image_tag=$( (git symbolic-ref -q --short HEAD || git describe --tags --exact-match) | tr / -)
          echo $image_tag

  build-pg:
    name: Build generic PostgreSQL image from sources
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    outputs:
      pg_image: ${{ env.TAG }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set env variables from defaults.json
      run: |
        for key in $(jq -r 'keys[]' defaults.json); do
          echo "$key=$(cat defaults.json | jq -r --arg key "$key" '.[$key]')" >> $GITHUB_ENV
        done

    # Inputs have priority over defaults.json.
    - name: Evaluate E2E workflow inputs
      run: |
        if [[ -n "${{ github.event.inputs.major_version }}" ]]; then
          echo "PG_MAJOR=${{ github.event.inputs.major_version }}" >> $GITHUB_ENV
        fi

    - name: Set tag and optional extra tag
      run: |
        TAG="${{ env.REGISTRY }}:${{ env.PG_MAJOR }}-build-${{ github.run_number }}"
        EXTRA_TAG=""
        if [[ "${{ github.event.inputs.extra_tag }}" != "" ]]; then
          EXTRA_TAG="${{ env.REGISTRY }}:${{ github.event.inputs.extra_tag }}"
        fi
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "EXTRA_TAG=${EXTRA_TAG}" >> $GITHUB_ENV

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        load: false
        tags: |
          ${{ env.TAG }}
          ${{ env.EXTRA_TAG }}
        build-args: |
          PG_REPO=${{ github.event.inputs.pg_repo }}
          PG_BRANCH=${{ github.event.inputs.pg_branch }}

  generate-summary:
    name: PostgreSQL Image Build summary
    runs-on: ubuntu-24.04
    needs:
      - build-pg
    steps:
      - name: Output summary
        run: |
          pg_major="${{ needs.build-pg.outputs.pg_major }}"
          image="${{ needs.build-pg.outputs.pg_image }}"
          imageURL="https://${image}"
          echo "# PostgreSQL Image Build summary" >> $GITHUB_STEP_SUMMARY
          echo "**Container Image**: [$image]($imageURL)" >> $GITHUB_STEP_SUMMARY
          echo "## CloudNativePG Cluster definition" >> $GITHUB_STEP_SUMMARY
          echo "You can create a cluster in CloudNativePG running this image:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`sh" >> $GITHUB_STEP_SUMMARY
          echo "(cat <<EOF" >> $GITHUB_STEP_SUMMARY
          echo "apiVersion: postgresql.cnpg.io/v1" >> $GITHUB_STEP_SUMMARY
          echo "kind: Cluster" >> $GITHUB_STEP_SUMMARY
          echo "metadata:" >> $GITHUB_STEP_SUMMARY
          echo "  name: pg-$pg_major-build" >> $GITHUB_STEP_SUMMARY
          echo "spec:" >> $GITHUB_STEP_SUMMARY
          echo "  imageName: $image" >> $GITHUB_STEP_SUMMARY
          echo "  instances: 3" >> $GITHUB_STEP_SUMMARY
          echo "  storage:" >> $GITHUB_STEP_SUMMARY
          echo "    size: 1Gi" >> $GITHUB_STEP_SUMMARY
          echo "EOF" >> $GITHUB_STEP_SUMMARY
          echo ") | kubectl apply -f -" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
