name: Build Commitfest Container Images

on:
  workflow_dispatch:
    inputs:
      commitfest_id:
        description: "ID of the Commitfest"
        required: false
        default: ""
      patch_id:
        description: "ID of the Patch"
        required: false
        default: ""

# set up environment variables to be used across all the jobs
env:
  REGISTRY: "ghcr.io/cloudnative-pg/postgresql-trunk"
  TAG: "commitfest-master"
  BRANCH: "master"

defaults:
  run:
    # default failure handling for shell scripts in 'run' steps
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build-pg:
    name: Build the patch for PostgreSQL
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set commitfest branch and tag
      if: github.event.inputs.commitfest_id != '' && github.event.inputs.patch_id != ''
      run: |
        BRANCH="commitfest/${{ github.event.inputs.commitfest_id }}/${{ github.event.inputs.patch_id }}"
        TAG=${BRANCH////-}
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        load: false
        tags: |
          ${{ env.REGISTRY }}:${{ env.TAG }}
        build-args: |
          PG_REPO=https://github.com/postgresql-cfbot/postgresql.git
          PG_BRANCH=${{ env.BRANCH }}
